# 
# Makefile.lib
# Created: Mon Jan  8 07:18:08 2001 by tek@wiw.org
# Revised: Sun Jul 15 02:03:35 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

### raster and event
ifeq ($(TARGET),unix-x11)
RASTERMODS=rastrx11.o
EVENTMODS=eventx11.o
AUDIOMODS=audnul.o
endif
ifeq ($(TARGET),linux-x11)
RASTERMODS=rastrx11.o
EVENTMODS=eventx11.o
AUDIOMODS=audoss.o
endif
ifeq ($(TARGET),unix-svgalib)
RASTERMODS=rastrvgl.o
EVENTMODS=eventvgl.o
AUDIOMODS=audnul.o
endif
ifeq ($(TARGET),linux-svgalib)
RASTERMODS=rastrvgl.o
EVENTMODS=eventvgl.o
AUDIOMODS=audoss.o
endif
ifeq ($(TARGET),dos)
RASTERMODS=rastrdos.o
EVENTMODS=eventdos.o kbddos.o
AUDIOMODS=auddos.o
endif

# default
ifndef RASTERMODS
RASTERMODS=rastrnul.o
EVENTMODS=eventnul.o
AUDIOMODS=audnul.o
endif

### system dependant stuff
ifeq ($(TARGETOS),unix)
SYSTEMMODS=memstd.o errorstd.o filestd.o timeunx.o \
           randstd.o
endif

# default
ifndef SYSTEMMODS
SYSTEMMODS=memnul.o errornul.o filenul.o timenul.o \
           randnul.o
endif

### generic stuff
GENERICMODS=errorsk.o set.o util.o fontgen.o samplgen.o wav.o s3mgen.o \
            spritgen.o tilegen.o mangrgen.o

### image related modules
IMAGEMODS=colorgen.o imagegen.o tga.o pcx.o blitcom.o collicom.o

ifeq ($(TARGETARCH),x86)
IMAGEMODS := $(IMAGEMODS) blitx86.o colligen.o \
             acompgen.o
SYSTEMMODS := $(SYSTEMMODS) memcpstd.o #memcpx86.o
endif
ifeq ($(TARGETARCH),generic)
IMAGEMODS := $(IMAGEMODS) blitgen.o colligen.o \
             acompgen.o
SYSTEMMODS := $(SYSTEMMODS) memcpstd.o
endif

### libdentata

MODULES=$(RASTERMODS) $(EVENTMODS) $(SYSTEMMODS) $(GENERICMODS) $(IMAGEMODS) \
        $(AUDIOMODS)

libdentata.a: $(MODULES)
	$(RM) $@
	$(AR) rc $@ $(MODULES)
	ranlib $@

libclean:
	$(RM) *.o

libdistclean: libclean
	$(RM) libdentata.a

# EOF Makefile.lib
