# 
# Makefile.docs
# Created: Sat Feb 24 19:09:17 2001 by tek@wiw.org
# Revised: Sat Feb 24 19:30:58 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

docs: manual.pdf

manual.pdf:
#	pdflatex main.tex

docsclean:
	rm -f *~

docsrealclean: docsclean

# EOF Makefile.docs