# 
# Makefile.docs
# Created: Sat Feb 24 19:09:17 2001 by tek@wiw.org
# Revised: Fri Jun 22 18:04:21 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

docs: manual.pdf

manual.pdf: docs/main.tex
	pdflatex docs/main.tex
	pdflatex docs/main.tex
	mv main.pdf manual.pdf

docsclean:
	rm -f *.toc *.log *.aux main.pdf

docsdistclean: docsclean
	rm -f manual.pdf

# EOF Makefile.docs
