# 
# Makefile.doc
# Created: Sat Feb 24 19:09:17 2001 by tek@wiw.org
# Revised: Sat Jun 23 04:16:35 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

docs: manual.pdf

docs/main.tex: docs/funcref.tex docs/intro.tex docs/graphics.tex \
               docs/input.tex docs/sound.tex docs/evrythng.tex \
               docs/devintro.tex docs/gfxintrn.tex

manual.pdf: docs/main.tex
	pdflatex docs/main.tex
	pdflatex docs/main.tex
	mv main.pdf manual.pdf

docs/funcref.tex: include/dentata/*.h tools/genfref.pl
	perl ./tools/genfref.pl ./include/dentata > docs/funcref.tex

docsclean:
	$(RM) *.toc *.log *.aux main.pdf

docsdistclean: docsclean
	$(RM) manual.pdf docs/funcref.tex

# EOF Makefile.doc
