# 
# Makefile.tests
# Created: Mon Jan  8 07:33:59 2001 by tek@wiw.org
# Revised: Thu Apr 19 04:06:41 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

TESTTOOLS=$(CURDIR)/tests/test-set
GENERATEDTESTS=test-image
TESTS=$(CURDIR)/tests/test-set.sh
PROFILES=

tests: $(TESTS) $(GENERATEDTESTS)
profile: $(PROFILES)

$(TESTS) $(PROFILES): libdentata.a
	$(CURDIR)/$@

# dependencies for individual tests
test-set.sh: test-set

$(GENERATEDTESTS): %: %.o
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS) -ldentata
	$(CURDIR)/$@

$(TESTTOOLS): %: %.o
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS) -ldentata

testsclean:
	rm -f *~ *.o

testsrealclean: testsclean
	rm -f $(GENERATEDTESTS)

# EOF Makefile
