# 
# Makefile.tests
# Created: Mon Jan  8 07:33:59 2001 by tek@wiw.org
# Revised: Sun Jun 17 02:16:08 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

TESTTOOLS=./tests/test-set
GENERATEDTESTS=./tests/test-image
TESTS=./tests/test-set.sh
PROFILES=

check: $(TESTS) $(GENERATEDTESTS)
profile: $(PROFILES)

$(TESTS) $(PROFILES): libdentata.a
	./$@

# dependencies for individual tests
test-set.sh: test-set

$(GENERATEDTESTS): %: %.o
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS) -ldentata
	./$@

$(TESTTOOLS): %: %.o
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS) -ldentata

testsclean:
	rm -f ./tests/*~ ./tests/*.o

testsdistclean: testsclean
	rm -f $(GENERATEDTESTS)

# EOF Makefile
