# 
# Makefile.lib
# Created: Mon Jan  8 07:18:08 2001 by tek@wiw.org
# Revised: Sun Jun 17 02:20:30 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

### raster and event
ifeq ($(TARGETGFX),x11)
RASTERMODS=rastrx11.o
EVENTMODS=eventx11.o
endif
ifeq ($(TARGETGFX),svgalib)
RASTERMODS=rastrvgl.o
EVENTMODS=eventvgl.o
endif

# default
ifndef RASTERMODS
RASTERMODS=rastrnul.o
EVENTMODS=eventnul.o
endif

### system dependant stuff
ifeq ($(TARGETOS),unix)
SYSTEMMODS=memstd.o errorstd.o filestd.o timeunx.o \
           randstd.o
endif

# default
ifndef SYSTEMMODS
SYSTEMMODS=memnul.o errornul.o filenul.o timenul.o \
           randnul.o
endif

### generic stuff
GENERICMODS=errorsk.o set.o util.o fontgen.o samplgen.o wav.o s3mgen.o

### image related modules
IMAGEMODS=colorgen.o imagegen.o spritgen.o tga.o pcx.o blitcom.o \
          collicom.o

ifeq ($(TARGETARCH),x86)
IMAGEMODS := $(IMAGEMODS) blitx86.o colligen.o \
             acompgen.o
endif

ifeq ($(TARGETARCH),generic)
IMAGEMODS := $(IMAGEMODS) blitgen.o colligen.o \
             acompgen.o
endif

### libdentata

MODULES=$(RASTERMODS) $(EVENTMODS) $(SYSTEMMODS) $(GENERICMODS) $(IMAGEMODS)

libdentata.a: $(MODULES)
	rm -f $@
	$(AR) rc $@ $(MODULES)
	ranlib $@

libclean:
	rm -f *.o

libdistclean: libclean
	rm -f libdentata.a

# EOF Makefile.lib
