#!/usr/bin/perl
# 
# genfref.pl
# Created: Sat Jun 23 02:29:42 2001 by tek@wiw.org
# Revised: Sun Jun 24 10:26:30 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

use strict;
use IO::File;

# Header
print "%\n% Generated by genfref.pl on ".localtime()." by ".`id -un`."%\n\n";

# For each header file
for(glob($ARGV[0].'/*.h')) {
  my (@com, $i, $j, %modinfo);

  # Extract comments
  @com = extractcom($_);
  # Parse comments
  for($i = 0; $i <= $#com; $i++) {
    $_ = $com[$i];

    # mangle for TeX
    &texmangle;

    if($i == 0) {
      s/.*Module: ([^\n]*)\n//s;
      # Create a section
      if($1 ne '') {
	print "\\section{$1}\n\\label{sec:fref$1}\n";
      }
      # Write top-of-file notes in.
      s/ \*\//\n/;
      s/ \*\n/\n/g;
      s/ \* //g;
      print "$_\n";
    } else {
      @_ = split /\n/;
      if($_[1] =~ /(d\\_\w+.*?)\(/ ||
         $_[1] =~ /(d\\_\w+\\_t)/) {
	print "\\subsection{$1}\n";
	$_ = $1;
	s/\\_//g;
	print "\\label{sec:frefsub$_}\n\n";
      }
      for($j = 1; $j <= $#_; $j++) {
	$_ = $_[$j];

	# Write function fu
        print writefuncinfo($j, @_);
      }
    }
  }
}

exit 0;

sub extractcom {
  my $in;

  $in = new IO::File($_[0], 'r') or die $!;
  undef $/;

  $_ = $in->getline();
  @_ = ();
  # only grabs /** comments intentionally.
  while(s/(\/\*\*\n.*?\*\/)//s) {
    $_[$#_+1] = ($1."\n\n");
  }

  return @_;
}

sub writefuncinfo {
  my $i = shift;
  $_ = $_[$i];
  $i++;

  if(/ \*[ \/]?/) {
    s/ \*[ \/]?//;

    s/(Takes): /\\noindent {\\bf $1}: /;
    s/(Returns): /\\noindent {\\bf $1}: /;
    s/(Members): /\\noindent {\\bf $1}: /;

    if($i == 2) {
      $_ = "{\\tt $_}\n\n";
    } else {
      if($_[$i] =~ /\w+ - /) {
	if($_[$i] !~ /Takes/ &&
	   $_[$i] !~ /Returns/ &&
	   $_[$i] !~ /Members/) {
	  $_[$i] =~ s/(\w+) - /\\indent {\\tt $1} - /;
	} else {
	  $_[$i] =~ s/([\w,]+) - /{\\tt $1} - /;
	}
	$_ .= "\n";
      }
      $_ .= "\n";
    }
  }

  return $_;
}

sub texmangle {
  s/\\/\$\\backslash\$/g;
  s/[{}]/\\&/g;
  s/_/\\_/g;
  s/\"/\\\"/g;
  s/</\$<\$/g;
  s/>/\$>\$/g;
}

# EOF genfref.pl
