#!/usr/bin/perl
# 
# genfref.pl
# Created: Sat Jun 23 02:29:42 2001 by tek@wiw.org
# Revised: Sat Jun 23 03:47:59 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

use strict;
use IO::File;

# Header
print "%\n% Generated by genfref.pl on ".localtime()." by ".`id -un`."%\n\n";

# For each header file
for(glob($ARGV[0].'/*.h')) {
  my (@com, $i, $j, %modinfo);

  # Extract comments
  @com = extractcom($_);
  # Parse comments
  for($i = 0; $i <= $#com; $i++) {
    $_ = $com[$i];
    # mangle for TeX
    s/\\/\$\\backslash\$/g;
    s/[{}]/\\&/g;
    s/"/\"/g;
    s/_/\\_/g;
    if($i == 0) {
      s/Module: (.*)\n//;
      # Create a section
      if($1 ne '') {
	print "\\section{$1}\n\\label{sec:fref$1}\n";
      }
      # Write top-of-file notes in.
      if(/ \*\n \* ((?:.*\n)+)\n \*\//) {
	print "$1\n";
      }
    } else {
      @_ = split /\n/;
      if($_[1] =~ /(d\\_\w+.*?)\(/) {
	print "\\subsection{$1}\n";
	$j = $1;
	$j =~ s/\\_//g;
	print "\\label{sec:frefsub$j}\n\n";
      }
      for($j = 0; $j <= $#_; $j++) {
	$_ = $_[$j];
	
	# Write function fu
	if(/ \*[ \/]?/) {
	  s/ \*[ \/]?//;

	  s/(Takes): /{\\bf $1}: /;
	  s/(Returns): /{\\bf $1}: /;

	  if($j == 1) {
	    print "{\\tt $_}\n\n";
	  } else {
	    print "$_\n";
	  }
	}
      }
    }
  }
}

exit 0;

sub extractcom {
  my $in;

  $in = new IO::File($_[0], 'r') or die $!;
  undef $/;

  $_ = $in->getline();
  @_ = ();
  # only grabs /** comments intentionally.
  while(s/(\/\*\*\n.*?\*\/)//s) {
    $_[$#_+1] = ($1."\n\n");
  }

  return @_;
}

# EOF genfref.pl
