# 
# Makefile
# Created: Mon Jan  8 07:33:59 2001 by tek@wiw.org
# Revised: Sat Feb 24 19:16:29 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

GENERATEDDEMOS=
DEMOS=$(GENERATEDDEMOS)

default: $(DEMOS)

clean:
	rm -f *~ *.o

realclean: clean
	rm -f $(GENERATEDDEMOS)

# EOF Makefile
