# 
# Makefile
# Created: Sat Feb 24 19:09:17 2001 by tek@wiw.org
# Revised: Sat Feb 24 19:30:58 2001 by tek@wiw.org
# Copyright 2001 Julian E. C. Squires (tek@wiw.org)
# This program comes with ABSOLUTELY NO WARRANTY.
# $Id$
# 
#

.PHONY: default clean realclean

default: manual.pdf

manual.pdf:
#	pdflatex main.tex

clean:
	rm -f *~

realclean: clean

# EOF Makefile